title:             Hochal's Blog
email:             748868@gmail.com
description:       A Blog by A Toddler
author:            Hochal
baseurl:           ""
url:               "http://123.github.io"

# Social Profiles
# twitter_username:  SBootstrap
github_username:   hochal
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
